### ISSUE TITLE
Reports `case is redundant` when the case is unique

### ISSUE THREAD

**Issue by lambduli** [boyland/sasylf#119] opened 2023-06-25 01:42 UTC
I was trying the exercise from the YT video. The `bad-fact` one.

Here is the lemma:
```
lemma bad-fact:
  forall imp: 2 + 2 = 3
  exists contradiction

  proof by case analysis on imp:
    case rule

      ds2p: 1 + 2 = 2
      ---------------- sum-s
      dsc: 2 + 2 = 3

    is
      proof by case analysis on ds2p:
      // THIS ONE!
        case rule

          ds1p: 0 + 2 = 2
          ---------------- sum-s
          ds1c: 1 + 2 = 2

        is
          proof by case analysis on ds1p:
          end case analysis
        end case
      end case analysis
    end case
  end case analysis
end lemma
```

And it tells me that the marked case is redundant (already handled).

I don't know what is going on, when I omit it, it complains that it should be handled though.

For brevity, I am leaving out the judgements and syntax—they are defined as in the first example.
Thanks a lot!

I also get the same issue for this one:
```
theorem sum-s-rh: forall d1: n1 + n2 = n3
				  exists n1 + (S n2) = (S n3).

proof by case analysis on d1:

	case rule

		_: n1' + n2 = n3
		------------------ sum-s
		_: S n1' + n2 = n3

	is proof by unproved
	end case

	case rule

		------------ sum-z
		_: 0 + n = n

	is
		_: Z + S n = S n by rule sum-z
	end case
end case analysis
end theorem
```

It tells me that my `sum-s` case is redundant (already handled). I don't see how.

**Comment by boyland** [comment] 2023-06-25 02:30
Hmm.  The error message is confusing/wrong.  It should say:
"The case is invalid"

The problem is that the sum-s axiom requires that the result below the line to be one more than the result above the line.  Your first proof has:
```
          ds1p: 0 + 2 = 2
          ---------------- sum-s
          ds1c: 1 + 2 = 2
```
and the second proof has a similar problem.
I accept this as a bad error message.

**Comment by lambduli** [comment] 2023-06-25 09:26
Oh my! The `2` after the `=` in the premise is wrong, right?

In the second proof that is just me being tired, in the first one I think I'll need to think more about how to get to contradiction.

Thanks!

**Comment by boyland** [comment] 2023-08-04 17:18
Fixed in trunk.  Fix will be in next release.

**Closed by boyland** 2023-08-04 17:18 UTC
